services:
  - type: web
    name: whispr
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: whispr_production
          property: connectionString
      - key: DATABASE_HOST
        fromDatabase:
          name: whispr_production
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: whispr_production
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: whispr_production
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: whispr_production
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: whispr_production
          property: password
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: whispr_production
    databaseName: whispr_production
    plan: free
    ipAllowList: [] 